apiVersion: v1
kind: Service
metadata:
  name: rapidnotes-web-svc
  labels:
    app: rapidnotes-web
spec:
  ports:
    - port: 80
  selector:
    app: rapidnotes-web
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: rapidnotes-web-deploy
  labels:
    app: rapidnotes-web
spec:
  selector:
    matchLabels:
      app: rapidnotes-web
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rapidnotes-web
        tier: frontend
    spec:
      containers:
      - name: rapidnotes-web
        image: a27818/rapidnotes:web-v3
        ports:
        - containerPort: 80
